language: node_js

node_js:
  - "node"

services:
  - postgresql

  before_script:
  - psql -c 'create database test_db;' -U postgres

env:
  - TEST_DIR=task_1
  - TEST_DIR=task_2
  global:
  - PGPORT=5433
script: cd $TEST_DIR && npm install && npm test
